### ISSUE TITLE
3rd Party Authentication

### ISSUE THREAD

**Issue by transcental** [RayhanADev/Replit-User-Search-v3#1]
How would you login with Google, GitHub or ~Facebook~? Replit supports these login systems.....

Is it limited to username + password only accounts?

**Comment by rayhanadev** [comment]
I added a method to login via the `connect.sid` token which should universalize logins and make it seem less shady. The SID login url is at https://replit-user-search-v3.rayhanadev.repl.co/login?useSid=true and it's the same process to grab the cookie as other Replit applications.

To learn how to get your `connect.sid` cookie visit [this tutorial](https://replit.com/talk/learn/How-to-Get-Your-SID-Cookie/145979).

**Comment by transcental** [comment]
Maybe you should add a note to the ReplShare post saying that if you use Google, GitHub or Facebook that you need to use the SID method?

Sorry for the late reply, I missed the email from GitHub.

**Comment by rayhanadev** [comment]
Gotcha, I'll add that!

**Comment by rayhanadev** [comment]
Done :)

> **What If I Used Google, Github, etc.?**
Then try [logging in via SID](https://replit-user-search-v3.rayhanadev.repl.co/login?useSid=true). How do you get your SID, it's very simple. Just read [this tutorial](https://replit.com/talk/learn/How-to-Get-Your-SID-Cookie/145979)!

~ From the updated post
